<a href="https://colab.research.google.com/github/sayashraaj/BTP/blob/main/BTP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the DataFrame

import pandas as pd
url = "https://raw.githubusercontent.com/sayashraaj/Dump/main/TrainScheduleDB.csv"
df = pd.read_csv(url, encoding='cp1252')

df.head(60)

,TrainId,TrainName,StationId,StationName,ScheduledArrival,ScheduledDeparture,Distance,Day
0,22981,KOTA - SRIGANGANAGAR SF EXPRESS,KOTA,KOTA JUNCTION,Source,17:20,0.0,1
1,22981,KOTA - SRIGANGANAGAR SF EXPRESS,KPTN,KESHORAI PATAN,17:35,17:37,13.3,1
2,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LKE,LAKHERI,18:07,18:09,60.6,1
3,22981,KOTA - SRIGANGANAGAR SF EXPRESS,IDG,INDARGARH SUMERGANJ MANDI,18:18,18:20,71.4,1
4,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SWM,SAWAI MADHOPUR JUNCTION,19:00,19:15,107.9,1
5,22981,KOTA - SRIGANGANAGAR SF EXPRESS,CKB,CHAUTH KA BARWARA,19:45,19:47,129.9,1
6,22981,KOTA - SRIGANGANAGAR SF EXPRESS,ISA,ISARDA,20:00,20:02,147.8,1
7,22981,KOTA - SRIGANGANAGAR SF EXPRESS,BNLW,BANASTHALI NIWAI,20:21,20:22,173.7,1
8,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DPA,DURGAPURA,21:13,21:16,232.3,1
9,22981,KOTA - SRIGANGANAGAR SF EXPRESS,JP,JAIPUR JUNCTION,21:35,21:45,239.7,1
10,22981,KOTA - SRIGANGANAGAR SF EXPRESS,JOB,ASALPUR JOBNER,22:11,22:13,276.4,1
11,22981,KOTA - SRIGANGANAGAR SF EXPRESS,FL,PHULERA JUNCTION,22:45,22:47,294.3,1
12,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SBR,SAMBHAR LAKE,22:54,22:56,301.9,1
13,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NAC,NAWA CITY,23:20,23:22,329.5,1
14,22981,KOTA - SRIGANGANAGAR SF EXPRESS,MKN,MAKRANA JUNCTION,23:58,00:01,359.1,1
15,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DNA,DEGANA JUNCTION,00:39,00:42,402.8,2
16,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NGO,NAGAUR,02:20,02:25,502.3,2
17,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NOK,NOKHA,03:04,03:06,554.0,2
18,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DSO,DESHNOKE,03:31,03:33,586.1,2
19,22981,KOTA - SRIGANGANAGAR SF EXPRESS,BKN,BIKANER JUNCTION,04:30,04:40,618.1,2
20,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LGH,LALGARH JUNCTION,04:50,04:52,622.0,2
21,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LKS,LUNKARANSAR,05:50,05:52,697.8,2
22,22981,KOTA - SRIGANGANAGAR SF EXPRESS,MHJ,MAHAJAN,06:22,06:24,737.4,2
23,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SOG,SURATGARH JUNCTION,07:25,07:30,800.0,2
24,22981,KOTA - SRIGANGANAGAR SF EXPRESS,PGK,PILI BANGAN,07:53,07:55,824.8,2
25,22981,KOTA - SRIGANGANAGAR SF EXPRESS,HMH,HANUMANGARH JUNCTION,08:30,08:50,850.5,2
26,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SDS,SADULSHAHR,09:20,09:22,888.3,2
27,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SGNR,SHRI GANGANAGAR,10:00,Destination,917.5,2
28,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SGNR,SHRI GANGANAGAR,Source,17:40,0.0,1
29,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SDS,SADULSHAHR,18:01,18:03,29.1,1
30,22982,SRIGANGANAGAR - KOTA SF EXPRESS,HMH,HANUMANGARH JUNCTION,18:40,19:00,67.0,1
31,22982,SRIGANGANAGAR - KOTA SF EXPRESS,PGK,PILI BANGAN,19:21,19:23,92.6,1
32,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SOG,SURATGARH JUNCTION,19:50,19:55,117.4,1
33,22982,SRIGANGANAGAR - KOTA SF EXPRESS,MHJ,MAHAJAN,20:41,20:43,180.1,1
34,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LKS,LUNKARANSAR,21:14,21:16,219.7,1
35,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LGH,LALGARH JUNCTION,22:16,22:18,295.5,1
36,22982,SRIGANGANAGAR - KOTA SF EXPRESS,BKN,BIKANER JUNCTION,22:50,23:05,299.4,1
37,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DSO,DESHNOKE,23:31,23:33,331.4,1
38,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NOK,NOKHA,23:59,00:01,363.5,1
39,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NGO,NAGAUR,00:42,00:47,415.2,2
40,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DNA,DEGANA JUNCTION,02:10,02:13,514.7,2
41,22982,SRIGANGANAGAR - KOTA SF EXPRESS,MKN,MAKRANA JUNCTION,02:47,02:50,558.3,2
42,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NAC,NAWA CITY,03:22,03:24,587.9,2
43,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SBR,SAMBHAR LAKE,04:03,04:05,615.6,2
44,22982,SRIGANGANAGAR - KOTA SF EXPRESS,FL,PHULERA JUNCTION,04:35,04:37,623.2,2
45,22982,SRIGANGANAGAR - KOTA SF EXPRESS,JOB,ASALPUR JOBNER,04:52,04:53,641.1,2
46,22982,SRIGANGANAGAR - KOTA SF EXPRESS,JP,JAIPUR JUNCTION,05:30,05:40,677.8,2
47,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DPA,DURGAPURA,05:46,05:49,685.2,2
48,22982,SRIGANGANAGAR - KOTA SF EXPRESS,BNLW,BANASTHALI NIWAI,06:28,06:30,743.8,2
49,22982,SRIGANGANAGAR - KOTA SF EXPRESS,ISA,ISARDA,06:55,06:57,769.7,2
50,22982,SRIGANGANAGAR - KOTA SF EXPRESS,CKB,CHAUTH KA BARWARA,07:10,07:11,787.6,2
51,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SWM,SAWAI MADHOPUR JUNCTION,07:45,07:55,809.6,2
52,22982,SRIGANGANAGAR - KOTA SF EXPRESS,IDG,INDARGARH SUMERGANJ MANDI,08:20,08:22,846.0,2
53,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LKE,LAKHERI,08:33,08:34,856.9,2
54,22982,SRIGANGANAGAR - KOTA SF EXPRESS,KPTN,KESHORAI PATAN,09:05,09:07,904.2,2
55,22982,SRIGANGANAGAR - KOTA SF EXPRESS,KOTA,KOTA JUNCTION,09:50,Destination,917.5,2
56,22985,UDAIPUR CITY - DELHI SARAI ROHILLA RAJASTHAN H...,UDZ,UDAIPUR CITY,Source,23:10,0.0,1
57,22985,UDAIPUR CITY - DELHI SARAI ROHILLA RAJASTHAN H...,MVJ,MAVLI JUNCTION,00:08,00:10,42.4,2
58,22985,UDAIPUR CITY - DELHI SARAI ROHILLA RAJASTHAN H...,CNA,CHANDERIYA,01:33,01:35,115.4,2
59,22985,UDAIPUR CITY - DELHI SARAI ROHILLA RAJASTHAN H...,BHL,BHILWARA,02:13,02:15,161.9,2

### Pre Processing

In [3]:
stations_list = ["WL", "TPJ"]
df_filtered = df[df["StationId"].isin(stations_list)]
df_filtered.head(5)

,TrainId,TrainName,StationId,StationName,ScheduledArrival,ScheduledDeparture,Distance,Day
49749,2193,TIRUNELVELI - JABALPUR SF FARE SPECIAL,TPJ,TIRUCHCHIRAPPALLI JUNCTION,00:05,00:10,313.8,2
49763,2193,TIRUNELVELI - JABALPUR SF FARE SPECIAL,WL,WARANGAL,19:43,19:45,1388.8,2
49786,2194,JABALPUR - TIRUNELVELI SF FARE SPECIAL,WL,WARANGAL,03:08,03:10,995.2,2
49800,2194,JABALPUR - TIRUNELVELI SF FARE SPECIAL,TPJ,TIRUCHCHIRAPPALLI JUNCTION,23:10,23:15,2071.5,2
51322,6001,CHENNAI EGMORE - TIRUNELVELI FARE SPECIAL,TPJ,TIRUCHCHIRAPPALLI JUNCTION,04:00,04:10,336.6,2

In [7]:
TrainId_dict = {}

for row in df_filtered.itertuples():
  TrainId_dict[row.TrainId] = []

TrainId_list = list(TrainId_dict.keys())

['2193',
 '2194',
 '6001',
 '6002',
 '6011',
 '6015',
 '6016',
 '6025',
 '6026',
 '6027',
 '6028',
 '6063',
 '6863',
 '6864',
 '7075',
 '7076',
 '7147',
 '7148',
 '7257',
 '7607',
 '7608',
 '8500',
 '11019',
 '11020',
 '11043',
 '11044',
 '11303',
 '11304',
 '12083',
 '12084',
 '12295',
 '12296',
 '12389',
 '12390',
 '12433',
 '12434',
 '12511',
 '12512',
 '12521',
 '12522',
 '12539',
 '12540',
 '12577',
 '12578',
 '12605',
 '12606',
 '12615',
 '12616',
 '12621',
 '12622',
 '12625',
 '12626',
 '12631',
 '12632',
 '12633',
 '12634',
 '12635',
 '12636',
 '12637',
 '12638',
 '12641',
 '12642',
 '12643',
 '12644',
 '12645',
 '12646',
 '12651',
 '12652',
 '12655',
 '12656',
 '12661',
 '12662',
 '12663',
 '12664',
 '12665',
 '12666',
 '12667',
 '12668',
 '12669',
 '12670',
 '12687',
 '12687-Slip',
 '12688',
 '12689',
 '12690',
 '12693',
 '12694',
 '12705',
 '12706',
 '12709',
 '12710',
 '12713',
 '12714',
 '12722-Slip',
 '12727',
 '12728',
 '12737',
 '12738',
 '12739',
 '12740',
 '12759',
 '12760',
 '12761',
 '12762',
 '12763',
 '12764',
 '12773',
 '12774',
 '12775',
 '12776',
 '12783',
 '12784',
 '12803',
 '12804',
 '12851',
 '12852',
 '12861',
 '12862',
 '12967',
 '12968',
 '12969',
 '12970',
 '14715',
 '14716',
 '14815',
 '14816',
 '15119',
 '15120',
 '16031',
 '16032',
 '16093',
 '16094',
 '16101',
 '16102',
 '16105',
 '16106',
 '16127',
 '16128',
 '16129',
 '16130',
 '16181',
 '16182',
 '16187',
 '16188',
 '16191',
 '16192',
 '16231',
 '16232',
 '16233',
 '16234',
 '16317',
 '16318',
 '16318-Slip',
 '16351',
 '16352',
 '16353',
 '16354',
 '16359',
 '16360',
 '16615',
 '16616',
 '16617',
 '16618',
 '16687',
 '16688',
 '16688-Slip',
 '16723',
 '16724',
 '16779',
 '16780',
 '16790',
 '16793',
 '16794',
 '16853',
 '16854',
 '16857',
 '16858',
 '16859',
 '16860',
 '16861',
 '16862',
 '16863',
 '16864',
 '17025',
 '17026',
 '17201',
 '17202',
 '17205',
 '17206',
 '17207',
 '17208',
 '17213',
 '17214',
 '17315',
 '17316',
 '17405',
 '17406',
 '17615',
 '17616',
 '18111',
 '18112',
 '18401',
 '18402',
 '18495',
 '18496',
 '18501',
 '18502',
 '18503',
 '18504',
 '18645',
 '18646',
 '22351',
 '22352',
 '22403',
 '22404',
 '22415',
 '22416',
 '22619',
 '22620',
 '22623',
 '22624',
 '22627',
 '22628',
 '22631',
 '22632',
 '22645',
 '22646',
 '22647',
 '22648',
 '22815',
 '22816',
 '22849',
 '22850',
 '56703',
 '56704',
 '56705',
 '56706',
 '56711',
 '56712',
 '56713',
 '56714',
 '56821',
 '56822',
 '56823',
 '56824',
 '56829',
 '56830',
 '56841',
 '56842',
 '57123',
 '57124',
 '57237',
 '57238',
 '57625',
 '57626',
 '57657',
 '57658',
 '67264',
 '67265',
 '67267',
 '67269',
 '67270',
 '76800',
 '76803',
 '76804',
 '76805',
 '76806',
 '76807',
 '76808',
 '76820',
 '76821',
 '76822',
 '76823',
 '76824',
 '76827',
 '76828',
 '76829',
 '76830',
 '76831',
 '76833',
 '76834',
 '76835',
 '76836',
 '76839',
 '76840',
 '76841',
 '76842',
 '76845',
 '76846',
 '76851',
 '76852',
 '76853',
 '76854',
 '77251',
 '77252',
 '82609',
 '12653',
 '12654',
 '12749',
 '12750',
 '22497',
 '22498',
 '22661',
 '22662',
 '22663',
 '22664',
 '56109',
 '56110',
 '56113',
 '56114',
 '82602',
 '16787',
 '22688']

In [ ]:
# Smaller DataFrame KOTA-SRIGANGANAGAR, 22981
# df1 = df[0:28]
df1 = df[0:56]
df1

,TrainId,TrainName,StationId,StationName,ScheduledArrival,ScheduledDeparture,Distance,Day
0,22981,KOTA - SRIGANGANAGAR SF EXPRESS,KOTA,KOTA JUNCTION,Source,17:20,0.0,1
1,22981,KOTA - SRIGANGANAGAR SF EXPRESS,KPTN,KESHORAI PATAN,17:35,17:37,13.3,1
2,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LKE,LAKHERI,18:07,18:09,60.6,1
3,22981,KOTA - SRIGANGANAGAR SF EXPRESS,IDG,INDARGARH SUMERGANJ MANDI,18:18,18:20,71.4,1
4,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SWM,SAWAI MADHOPUR JUNCTION,19:00,19:15,107.9,1
5,22981,KOTA - SRIGANGANAGAR SF EXPRESS,CKB,CHAUTH KA BARWARA,19:45,19:47,129.9,1
6,22981,KOTA - SRIGANGANAGAR SF EXPRESS,ISA,ISARDA,20:00,20:02,147.8,1
7,22981,KOTA - SRIGANGANAGAR SF EXPRESS,BNLW,BANASTHALI NIWAI,20:21,20:22,173.7,1
8,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DPA,DURGAPURA,21:13,21:16,232.3,1
9,22981,KOTA - SRIGANGANAGAR SF EXPRESS,JP,JAIPUR JUNCTION,21:35,21:45,239.7,1
10,22981,KOTA - SRIGANGANAGAR SF EXPRESS,JOB,ASALPUR JOBNER,22:11,22:13,276.4,1
11,22981,KOTA - SRIGANGANAGAR SF EXPRESS,FL,PHULERA JUNCTION,22:45,22:47,294.3,1
12,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SBR,SAMBHAR LAKE,22:54,22:56,301.9,1
13,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NAC,NAWA CITY,23:20,23:22,329.5,1
14,22981,KOTA - SRIGANGANAGAR SF EXPRESS,MKN,MAKRANA JUNCTION,23:58,00:01,359.1,1
15,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DNA,DEGANA JUNCTION,00:39,00:42,402.8,2
16,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NGO,NAGAUR,02:20,02:25,502.3,2
17,22981,KOTA - SRIGANGANAGAR SF EXPRESS,NOK,NOKHA,03:04,03:06,554.0,2
18,22981,KOTA - SRIGANGANAGAR SF EXPRESS,DSO,DESHNOKE,03:31,03:33,586.1,2
19,22981,KOTA - SRIGANGANAGAR SF EXPRESS,BKN,BIKANER JUNCTION,04:30,04:40,618.1,2
20,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LGH,LALGARH JUNCTION,04:50,04:52,622.0,2
21,22981,KOTA - SRIGANGANAGAR SF EXPRESS,LKS,LUNKARANSAR,05:50,05:52,697.8,2
22,22981,KOTA - SRIGANGANAGAR SF EXPRESS,MHJ,MAHAJAN,06:22,06:24,737.4,2
23,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SOG,SURATGARH JUNCTION,07:25,07:30,800.0,2
24,22981,KOTA - SRIGANGANAGAR SF EXPRESS,PGK,PILI BANGAN,07:53,07:55,824.8,2
25,22981,KOTA - SRIGANGANAGAR SF EXPRESS,HMH,HANUMANGARH JUNCTION,08:30,08:50,850.5,2
26,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SDS,SADULSHAHR,09:20,09:22,888.3,2
27,22981,KOTA - SRIGANGANAGAR SF EXPRESS,SGNR,SHRI GANGANAGAR,10:00,Destination,917.5,2
28,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SGNR,SHRI GANGANAGAR,Source,17:40,0.0,1
29,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SDS,SADULSHAHR,18:01,18:03,29.1,1
30,22982,SRIGANGANAGAR - KOTA SF EXPRESS,HMH,HANUMANGARH JUNCTION,18:40,19:00,67.0,1
31,22982,SRIGANGANAGAR - KOTA SF EXPRESS,PGK,PILI BANGAN,19:21,19:23,92.6,1
32,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SOG,SURATGARH JUNCTION,19:50,19:55,117.4,1
33,22982,SRIGANGANAGAR - KOTA SF EXPRESS,MHJ,MAHAJAN,20:41,20:43,180.1,1
34,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LKS,LUNKARANSAR,21:14,21:16,219.7,1
35,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LGH,LALGARH JUNCTION,22:16,22:18,295.5,1
36,22982,SRIGANGANAGAR - KOTA SF EXPRESS,BKN,BIKANER JUNCTION,22:50,23:05,299.4,1
37,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DSO,DESHNOKE,23:31,23:33,331.4,1
38,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NOK,NOKHA,23:59,00:01,363.5,1
39,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NGO,NAGAUR,00:42,00:47,415.2,2
40,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DNA,DEGANA JUNCTION,02:10,02:13,514.7,2
41,22982,SRIGANGANAGAR - KOTA SF EXPRESS,MKN,MAKRANA JUNCTION,02:47,02:50,558.3,2
42,22982,SRIGANGANAGAR - KOTA SF EXPRESS,NAC,NAWA CITY,03:22,03:24,587.9,2
43,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SBR,SAMBHAR LAKE,04:03,04:05,615.6,2
44,22982,SRIGANGANAGAR - KOTA SF EXPRESS,FL,PHULERA JUNCTION,04:35,04:37,623.2,2
45,22982,SRIGANGANAGAR - KOTA SF EXPRESS,JOB,ASALPUR JOBNER,04:52,04:53,641.1,2
46,22982,SRIGANGANAGAR - KOTA SF EXPRESS,JP,JAIPUR JUNCTION,05:30,05:40,677.8,2
47,22982,SRIGANGANAGAR - KOTA SF EXPRESS,DPA,DURGAPURA,05:46,05:49,685.2,2
48,22982,SRIGANGANAGAR - KOTA SF EXPRESS,BNLW,BANASTHALI NIWAI,06:28,06:30,743.8,2
49,22982,SRIGANGANAGAR - KOTA SF EXPRESS,ISA,ISARDA,06:55,06:57,769.7,2
50,22982,SRIGANGANAGAR - KOTA SF EXPRESS,CKB,CHAUTH KA BARWARA,07:10,07:11,787.6,2
51,22982,SRIGANGANAGAR - KOTA SF EXPRESS,SWM,SAWAI MADHOPUR JUNCTION,07:45,07:55,809.6,2
52,22982,SRIGANGANAGAR - KOTA SF EXPRESS,IDG,INDARGARH SUMERGANJ MANDI,08:20,08:22,846.0,2
53,22982,SRIGANGANAGAR - KOTA SF EXPRESS,LKE,LAKHERI,08:33,08:34,856.9,2
54,22982,SRIGANGANAGAR - KOTA SF EXPRESS,KPTN,KESHORAI PATAN,09:05,09:07,904.2,2
55,22982,SRIGANGANAGAR - KOTA SF EXPRESS,KOTA,KOTA JUNCTION,09:50,Destination,917.5,2

In [ ]:
# Declaring Node class

# class Node:
#   def __init__(self, TrainId, TrainName, StationId, StationName, ScheduledArrival, ScheduledDeparture, Day):
#     self.TrainId = TrainId
#     self.TrainName = TrainName
#     self.StationId = StationId
#     self.StationName = StationName
#     self.ScheduledArrival = ScheduledArrival
#     self.ScheduledDeparture = ScheduledDeparture
#     self.Day = Day
#     self.connectedTo = []

class Node:
  def __init__(self, TrainId, TrainName, StationId, StationName, Time, Day):
    self.TrainId = TrainId
    self.TrainName = TrainName
    self.StationId = StationId
    self.StationName = StationName
    self.Time = Time
    self.Day = Day
    self.connectedTo = []

In [ ]:
# Creating and storing nodes in nodesList
nodesList = []

for row in df1.itertuples():
  if row.ScheduledArrival=='Source':
    print("Source detected")
  else:
    nodesList.append(Node(row.TrainId, row.TrainName, row.StationId, row.StationName, row.ScheduledArrival, row.Day))
  if row.ScheduledDeparture=='Destination':
    print("Destination detected")
  else:
    nodesList.append(Node(row.TrainId, row.TrainName, row.StationId, row.StationName, row.ScheduledDeparture, row.Day))

Source detected
Destination detected
Source detected
Destination detected

In [ ]:
# Printing connectedTo []

def printConnectedTo(i):
  print("Node details", nodesList[i].TrainId, nodesList[i].Time, nodesList[i].Day)
  print("Printing connectedTo for Node",i)
  for x in nodesList[i].connectedTo:
    print("Connection:", x.TrainId, x.Time, x.Day)
  print("----------------------")

In [ ]:
# # Linking for same Train

# for i in range(0, len(nodesList)-1):
#   if nodesList[i].TrainId==nodesList[i+1].TrainId and nodesList[i].Time<nodesList[i+1].Time and :
#     nodesList[i].connectedTo.append(nodesList[i+1])
#   printConnectedTo(i)

for i in range(len(nodesList)-1):
  j=i+1
  nodeA = nodesList[i]
  nodeB = nodesList[j]
  # if i==j or nodeA.TrainId!=nodeB.TrainId or nodeA.Time>nodeB.Time or nodeA.Day>nodeB.Day:
  if i==j or nodeA.TrainId!=nodeB.TrainId:
    continue
  else:
    print("connecting",nodeA.TrainId, nodeA.Time, nodeA.Day,"to", nodeB.TrainId, nodeB.Time, nodeA.Day)
    nodeA.connectedTo.append(nodeB)

connecting 22981 17:20 1 to 22981 17:35 1
connecting 22981 17:35 1 to 22981 17:37 1
connecting 22981 17:37 1 to 22981 18:07 1
connecting 22981 18:07 1 to 22981 18:09 1
connecting 22981 18:09 1 to 22981 18:18 1
connecting 22981 18:18 1 to 22981 18:20 1
connecting 22981 18:20 1 to 22981 19:00 1
connecting 22981 19:00 1 to 22981 19:15 1
connecting 22981 19:15 1 to 22981 19:45 1
connecting 22981 19:45 1 to 22981 19:47 1
connecting 22981 19:47 1 to 22981 20:00 1
connecting 22981 20:00 1 to 22981 20:02 1
connecting 22981 20:02 1 to 22981 20:21 1
connecting 22981 20:21 1 to 22981 20:22 1
connecting 22981 20:22 1 to 22981 21:13 1
connecting 22981 21:13 1 to 22981 21:16 1
connecting 22981 21:16 1 to 22981 21:35 1
connecting 22981 21:35 1 to 22981 21:45 1
connecting 22981 21:45 1 to 22981 22:11 1
connecting 22981 22:11 1 to 22981 22:13 1
connecting 22981 22:13 1 to 22981 22:45 1
connecting 22981 22:45 1 to 22981 22:47 1
connecting 22981 22:47 1 to 22981 22:54 1
connecting 22981 22:54 1 to 22981 22:56 1
connecting 22981 22:56 1 to 22981 23:20 1
connecting 22981 23:20 1 to 22981 23:22 1
connecting 22981 23:22 1 to 22981 23:58 1
connecting 22981 23:58 1 to 22981 00:01 1
connecting 22981 00:01 1 to 22981 00:39 1
connecting 22981 00:39 2 to 22981 00:42 2
connecting 22981 00:42 2 to 22981 02:20 2
connecting 22981 02:20 2 to 22981 02:25 2
connecting 22981 02:25 2 to 22981 03:04 2
connecting 22981 03:04 2 to 22981 03:06 2
connecting 22981 03:06 2 to 22981 03:31 2
connecting 22981 03:31 2 to 22981 03:33 2
connecting 22981 03:33 2 to 22981 04:30 2
connecting 22981 04:30 2 to 22981 04:40 2
connecting 22981 04:40 2 to 22981 04:50 2
connecting 22981 04:50 2 to 22981 04:52 2
connecting 22981 04:52 2 to 22981 05:50 2
connecting 22981 05:50 2 to 22981 05:52 2
connecting 22981 05:52 2 to 22981 06:22 2
connecting 22981 06:22 2 to 22981 06:24 2
connecting 22981 06:24 2 to 22981 07:25 2
connecting 22981 07:25 2 to 22981 07:30 2
connecting 22981 07:30 2 to 22981 07:53 2
connecting 22981 07:53 2 to 22981 07:55 2
connecting 22981 07:55 2 to 22981 08:30 2
connecting 22981 08:30 2 to 22981 08:50 2
connecting 22981 08:50 2 to 22981 09:20 2
connecting 22981 09:20 2 to 22981 09:22 2
connecting 22981 09:22 2 to 22981 10:00 2
connecting 22982 17:40 1 to 22982 18:01 1
connecting 22982 18:01 1 to 22982 18:03 1
connecting 22982 18:03 1 to 22982 18:40 1
connecting 22982 18:40 1 to 22982 19:00 1
connecting 22982 19:00 1 to 22982 19:21 1
connecting 22982 19:21 1 to 22982 19:23 1
connecting 22982 19:23 1 to 22982 19:50 1
connecting 22982 19:50 1 to 22982 19:55 1
connecting 22982 19:55 1 to 22982 20:41 1
connecting 22982 20:41 1 to 22982 20:43 1
connecting 22982 20:43 1 to 22982 21:14 1
connecting 22982 21:14 1 to 22982 21:16 1
connecting 22982 21:16 1 to 22982 22:16 1
connecting 22982 22:16 1 to 22982 22:18 1
connecting 22982 22:18 1 to 22982 22:50 1
connecting 22982 22:50 1 to 22982 23:05 1
connecting 22982 23:05 1 to 22982 23:31 1
connecting 22982 23:31 1 to 22982 23:33 1
connecting 22982 23:33 1 to 22982 23:59 1
connecting 22982 23:59 1 to 22982 00:01 1
connecting 22982 00:01 1 to 22982 00:42 1
connecting 22982 00:42 2 to 22982 00:47 2
connecting 22982 00:47 2 to 22982 02:10 2
connecting 22982 02:10 2 to 22982 02:13 2
connecting 22982 02:13 2 to 22982 02:47 2
connecting 22982 02:47 2 to 22982 02:50 2
connecting 22982 02:50 2 to 22982 03:22 2
connecting 22982 03:22 2 to 22982 03:24 2
connecting 22982 03:24 2 to 22982 04:03 2
connecting 22982 04:03 2 to 22982 04:05 2
connecting 22982 04:05 2 to 22982 04:35 2
connecting 22982 04:35 2 to 22982 04:37 2
connecting 22982 04:37 2 to 22982 04:52 2
connecting 22982 04:52 2 to 22982 04:53 2
connecting 22982 04:53 2 to 22982 05:30 2
connecting 22982 05:30 2 to 22982 05:40 2
connecting 22982 05:40 2 to 22982 05:46 2
connecting 22982 05:46 2 to 22982 05:49 2
connecting 22982 05:49 2 to 22982 06:28 2
connecting 22982 06:28 2 to 22982 06:30 2
connecting 22982 06:30 2 to 22982 06:55 2
connecting 22982 06:55 2 to 22982 06:57 2
connecting 22982 06:57 2 to 22982 07:10 2
connecting 22982 07:10 2 to 22982 07:11 2
connecting 22982 07:11 2 to 22982 07:45 2
connecting 22982 07:45 2 to 22982 07:55 2
connecting 22982 07:55 2 to 22982 08:20 2
connecting 22982 08:20 2 to 22982 08:22 2
connecting 22982 08:22 2 to 22982 08:33 2
connecting 22982 08:33 2 to 22982 08:34 2
connecting 22982 08:34 2 to 22982 09:05 2
connecting 22982 09:05 2 to 22982 09:07 2
connecting 22982 09:07 2 to 22982 09:50 2

In [ ]:
# Connected nodes with same StationId

for i in range(len(nodesList)):
  for j in range(len(nodesList)):
    nodeA = nodesList[i]
    nodeB = nodesList[j]
    if i==j or nodeA.StationId!=nodeB.StationId or nodeA.TrainId==nodeB.TrainId or nodeA.Time>nodeB.Time or nodeA.Day>nodeB.Day:
      continue
    else:
      print("connecting",nodeA.TrainId, nodeA.Time, nodeA.Day,"to", nodeB.TrainId, nodeB.Time, nodeA.Day)
      nodeA.connectedTo.append(nodeB)

connecting 22981 00:01 1 to 22982 02:47 1
connecting 22981 00:01 1 to 22982 02:50 1
connecting 22981 00:39 2 to 22982 02:10 2
connecting 22981 00:39 2 to 22982 02:13 2
connecting 22981 00:42 2 to 22982 02:10 2
connecting 22981 00:42 2 to 22982 02:13 2
connecting 22982 00:01 1 to 22981 03:04 1
connecting 22982 00:01 1 to 22981 03:06 1
connecting 22982 00:42 2 to 22981 02:20 2
connecting 22982 00:42 2 to 22981 02:25 2
connecting 22982 00:47 2 to 22981 02:20 2
connecting 22982 00:47 2 to 22981 02:25 2

In [ ]:
for i in range(len(nodesList)):
  printConnectedTo(i)

Node details 22981 17:20 1
Printing connectedTo for Node 0
Connection: 22981 17:35 1
----------------------
Node details 22981 17:35 1
Printing connectedTo for Node 1
Connection: 22981 17:37 1
----------------------
Node details 22981 17:37 1
Printing connectedTo for Node 2
Connection: 22981 18:07 1
----------------------
Node details 22981 18:07 1
Printing connectedTo for Node 3
Connection: 22981 18:09 1
----------------------
Node details 22981 18:09 1
Printing connectedTo for Node 4
Connection: 22981 18:18 1
----------------------
Node details 22981 18:18 1
Printing connectedTo for Node 5
Connection: 22981 18:20 1
----------------------
Node details 22981 18:20 1
Printing connectedTo for Node 6
Connection: 22981 19:00 1
----------------------
Node details 22981 19:00 1
Printing connectedTo for Node 7
Connection: 22981 19:15 1
----------------------
Node details 22981 19:15 1
Printing connectedTo for Node 8
Connection: 22981 19:45 1
----------------------
Node details 22981 19:45 1
Printing connectedTo for Node 9
Connection: 22981 19:47 1
----------------------
Node details 22981 19:47 1
Printing connectedTo for Node 10
Connection: 22981 20:00 1
----------------------
Node details 22981 20:00 1
Printing connectedTo for Node 11
Connection: 22981 20:02 1
----------------------
Node details 22981 20:02 1
Printing connectedTo for Node 12
Connection: 22981 20:21 1
----------------------
Node details 22981 20:21 1
Printing connectedTo for Node 13
Connection: 22981 20:22 1
----------------------
Node details 22981 20:22 1
Printing connectedTo for Node 14
Connection: 22981 21:13 1
----------------------
Node details 22981 21:13 1
Printing connectedTo for Node 15
Connection: 22981 21:16 1
----------------------
Node details 22981 21:16 1
Printing connectedTo for Node 16
Connection: 22981 21:35 1
----------------------
Node details 22981 21:35 1
Printing connectedTo for Node 17
Connection: 22981 21:45 1
----------------------
Node details 22981 21:45 1
Printing connectedTo for Node 18
Connection: 22981 22:11 1
----------------------
Node details 22981 22:11 1
Printing connectedTo for Node 19
Connection: 22981 22:13 1
----------------------
Node details 22981 22:13 1
Printing connectedTo for Node 20
Connection: 22981 22:45 1
----------------------
Node details 22981 22:45 1
Printing connectedTo for Node 21
Connection: 22981 22:47 1
----------------------
Node details 22981 22:47 1
Printing connectedTo for Node 22
Connection: 22981 22:54 1
----------------------
Node details 22981 22:54 1
Printing connectedTo for Node 23
Connection: 22981 22:56 1
----------------------
Node details 22981 22:56 1
Printing connectedTo for Node 24
Connection: 22981 23:20 1
----------------------
Node details 22981 23:20 1
Printing connectedTo for Node 25
Connection: 22981 23:22 1
----------------------
Node details 22981 23:22 1
Printing connectedTo for Node 26
Connection: 22981 23:58 1
----------------------
Node details 22981 23:58 1
Printing connectedTo for Node 27
Connection: 22981 00:01 1
----------------------
Node details 22981 00:01 1
Printing connectedTo for Node 28
Connection: 22981 00:39 2
Connection: 22982 02:47 2
Connection: 22982 02:50 2
----------------------
Node details 22981 00:39 2
Printing connectedTo for Node 29
Connection: 22981 00:42 2
Connection: 22982 02:10 2
Connection: 22982 02:13 2
----------------------
Node details 22981 00:42 2
Printing connectedTo for Node 30
Connection: 22981 02:20 2
Connection: 22982 02:10 2
Connection: 22982 02:13 2
----------------------
Node details 22981 02:20 2
Printing connectedTo for Node 31
Connection: 22981 02:25 2
----------------------
Node details 22981 02:25 2
Printing connectedTo for Node 32
Connection: 22981 03:04 2
----------------------
Node details 22981 03:04 2
Printing connectedTo for Node 33
Connection: 22981 03:06 2
----------------------
Node details 22981 03:06 2
Printing connectedTo for Node 34
Connection: 22981 03:31 2
----------------------
Node details 22981 03:31 2
Printing connectedTo for Node 35
Connection: 22981 03:33 2
----------------------
Node details 22981 03:33 2
Printing connectedTo for Node 36
Connection: 22981 04:30 2
----------------------
Node details 22981 04:30 2
Printing connectedTo for Node 37
Connection: 22981 04:40 2
----------------------
Node details 22981 04:40 2
Printing connectedTo for Node 38
Connection: 22981 04:50 2
----------------------
Node details 22981 04:50 2
Printing connectedTo for Node 39
Connection: 22981 04:52 2
----------------------
Node details 22981 04:52 2
Printing connectedTo for Node 40
Connection: 22981 05:50 2
----------------------
Node details 22981 05:50 2
Printing connectedTo for Node 41
Connection: 22981 05:52 2
----------------------
Node details 22981 05:52 2
Printing connectedTo for Node 42
Connection: 22981 06:22 2
----------------------
Node details 22981 06:22 2
Printing connectedTo for Node 43
Connection: 22981 06:24 2
----------------------
Node details 22981 06:24 2
Printing connectedTo for Node 44
Connection: 22981 07:25 2
----------------------
Node details 22981 07:25 2
Printing connectedTo for Node 45
Connection: 22981 07:30 2
----------------------
Node details 22981 07:30 2
Printing connectedTo for Node 46
Connection: 22981 07:53 2
----------------------
Node details 22981 07:53 2
Printing connectedTo for Node 47
Connection: 22981 07:55 2
----------------------
Node details 22981 07:55 2
Printing connectedTo for Node 48
Connection: 22981 08:30 2
----------------------
Node details 22981 08:30 2
Printing connectedTo for Node 49
Connection: 22981 08:50 2
----------------------
Node details 22981 08:50 2
Printing connectedTo for Node 50
Connection: 22981 09:20 2
----------------------
Node details 22981 09:20 2
Printing connectedTo for Node 51
Connection: 22981 09:22 2
----------------------
Node details 22981 09:22 2
Printing connectedTo for Node 52
Connection: 22981 10:00 2
----------------------
Node details 22981 10:00 2
Printing connectedTo for Node 53
----------------------
Node details 22982 17:40 1
Printing connectedTo for Node 54
Connection: 22982 18:01 1
----------------------
Node details 22982 18:01 1
Printing connectedTo for Node 55
Connection: 22982 18:03 1
----------------------
Node details 22982 18:03 1
Printing connectedTo for Node 56
Connection: 22982 18:40 1
----------------------
Node details 22982 18:40 1
Printing connectedTo for Node 57
Connection: 22982 19:00 1
----------------------
Node details 22982 19:00 1
Printing connectedTo for Node 58
Connection: 22982 19:21 1
----------------------
Node details 22982 19:21 1
Printing connectedTo for Node 59
Connection: 22982 19:23 1
----------------------
Node details 22982 19:23 1
Printing connectedTo for Node 60
Connection: 22982 19:50 1
----------------------
Node details 22982 19:50 1
Printing connectedTo for Node 61
Connection: 22982 19:55 1
----------------------
Node details 22982 19:55 1
Printing connectedTo for Node 62
Connection: 22982 20:41 1
----------------------
Node details 22982 20:41 1
Printing connectedTo for Node 63
Connection: 22982 20:43 1
----------------------
Node details 22982 20:43 1
Printing connectedTo for Node 64
Connection: 22982 21:14 1
----------------------
Node details 22982 21:14 1
Printing connectedTo for Node 65
Connection: 22982 21:16 1
----------------------
Node details 22982 21:16 1
Printing connectedTo for Node 66
Connection: 22982 22:16 1
----------------------
Node details 22982 22:16 1
Printing connectedTo for Node 67
Connection: 22982 22:18 1
----------------------
Node details 22982 22:18 1
Printing connectedTo for Node 68
Connection: 22982 22:50 1
----------------------
Node details 22982 22:50 1
Printing connectedTo for Node 69
Connection: 22982 23:05 1
----------------------
Node details 22982 23:05 1
Printing connectedTo for Node 70
Connection: 22982 23:31 1
----------------------
Node details 22982 23:31 1
Printing connectedTo for Node 71
Connection: 22982 23:33 1
----------------------
Node details 22982 23:33 1
Printing connectedTo for Node 72
Connection: 22982 23:59 1
----------------------
Node details 22982 23:59 1
Printing connectedTo for Node 73
Connection: 22982 00:01 1
----------------------
Node details 22982 00:01 1
Printing connectedTo for Node 74
Connection: 22982 00:42 2
Connection: 22981 03:04 2
Connection: 22981 03:06 2
----------------------
Node details 22982 00:42 2
Printing connectedTo for Node 75
Connection: 22982 00:47 2
Connection: 22981 02:20 2
Connection: 22981 02:25 2
----------------------
Node details 22982 00:47 2
Printing connectedTo for Node 76
Connection: 22982 02:10 2
Connection: 22981 02:20 2
Connection: 22981 02:25 2
----------------------
Node details 22982 02:10 2
Printing connectedTo for Node 77
Connection: 22982 02:13 2
----------------------
Node details 22982 02:13 2
Printing connectedTo for Node 78
Connection: 22982 02:47 2
----------------------
Node details 22982 02:47 2
Printing connectedTo for Node 79
Connection: 22982 02:50 2
----------------------
Node details 22982 02:50 2
Printing connectedTo for Node 80
Connection: 22982 03:22 2
----------------------
Node details 22982 03:22 2
Printing connectedTo for Node 81
Connection: 22982 03:24 2
----------------------
Node details 22982 03:24 2
Printing connectedTo for Node 82
Connection: 22982 04:03 2
----------------------
Node details 22982 04:03 2
Printing connectedTo for Node 83
Connection: 22982 04:05 2
----------------------
Node details 22982 04:05 2
Printing connectedTo for Node 84
Connection: 22982 04:35 2
----------------------
Node details 22982 04:35 2
Printing connectedTo for Node 85
Connection: 22982 04:37 2
----------------------
Node details 22982 04:37 2
Printing connectedTo for Node 86
Connection: 22982 04:52 2
----------------------
Node details 22982 04:52 2
Printing connectedTo for Node 87
Connection: 22982 04:53 2
----------------------
Node details 22982 04:53 2
Printing connectedTo for Node 88
Connection: 22982 05:30 2
----------------------
Node details 22982 05:30 2
Printing connectedTo for Node 89
Connection: 22982 05:40 2
----------------------
Node details 22982 05:40 2
Printing connectedTo for Node 90
Connection: 22982 05:46 2
----------------------
Node details 22982 05:46 2
Printing connectedTo for Node 91
Connection: 22982 05:49 2
----------------------
Node details 22982 05:49 2
Printing connectedTo for Node 92
Connection: 22982 06:28 2
----------------------
Node details 22982 06:28 2
Printing connectedTo for Node 93
Connection: 22982 06:30 2
----------------------
Node details 22982 06:30 2
Printing connectedTo for Node 94
Connection: 22982 06:55 2
----------------------
Node details 22982 06:55 2
Printing connectedTo for Node 95
Connection: 22982 06:57 2
----------------------
Node details 22982 06:57 2
Printing connectedTo for Node 96
Connection: 22982 07:10 2
----------------------
Node details 22982 07:10 2
Printing connectedTo for Node 97
Connection: 22982 07:11 2
----------------------
Node details 22982 07:11 2
Printing connectedTo for Node 98
Connection: 22982 07:45 2
----------------------
Node details 22982 07:45 2
Printing connectedTo for Node 99
Connection: 22982 07:55 2
----------------------
Node details 22982 07:55 2
Printing connectedTo for Node 100
Connection: 22982 08:20 2
----------------------
Node details 22982 08:20 2
Printing connectedTo for Node 101
Connection: 22982 08:22 2
----------------------
Node details 22982 08:22 2
Printing connectedTo for Node 102
Connection: 22982 08:33 2
----------------------
Node details 22982 08:33 2
Printing connectedTo for Node 103
Connection: 22982 08:34 2
----------------------
Node details 22982 08:34 2
Printing connectedTo for Node 104
Connection: 22982 09:05 2
----------------------
Node details 22982 09:05 2
Printing connectedTo for Node 105
Connection: 22982 09:07 2
----------------------
Node details 22982 09:07 2
Printing connectedTo for Node 106
Connection: 22982 09:50 2
----------------------
Node details 22982 09:50 2
Printing connectedTo for Node 107
----------------------

In [ ]:
# converting to nodes[]

nodes = []
nodesDict = {}
for i in range(len(nodesList)):
  nodes.append(i)
  nodesDict[nodesList[i]]=i
print(nodes)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107]

In [ ]:
# converting to links[(a,b)]
# node 29, 30 have multiple links

links = []

for i in range(len(nodesList)):
  for j in range(len(nodesList[i].connectedTo)):
    links.append((nodesDict[nodesList[i]], nodesDict[nodesList[i].connectedTo[j]]))

print(links)

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18), (18, 19), (19, 20), (20, 21), (21, 22), (22, 23), (23, 24), (24, 25), (25, 26), (26, 27), (27, 28), (28, 29), (28, 79), (28, 80), (29, 30), (29, 77), (29, 78), (30, 31), (30, 77), (30, 78), (31, 32), (32, 33), (33, 34), (34, 35), (35, 36), (36, 37), (37, 38), (38, 39), (39, 40), (40, 41), (41, 42), (42, 43), (43, 44), (44, 45), (45, 46), (46, 47), (47, 48), (48, 49), (49, 50), (50, 51), (51, 52), (52, 53), (54, 55), (55, 56), (56, 57), (57, 58), (58, 59), (59, 60), (60, 61), (61, 62), (62, 63), (63, 64), (64, 65), (65, 66), (66, 67), (67, 68), (68, 69), (69, 70), (70, 71), (71, 72), (72, 73), (73, 74), (74, 75), (74, 33), (74, 34), (75, 76), (75, 31), (75, 32), (76, 77), (76, 31), (76, 32), (77, 78), (78, 79), (79, 80), (80, 81), (81, 82), (82, 83), (83, 84), (84, 85), (85, 86), (86, 87), (87, 88), (88, 89), (89, 90), (90, 91), (91, 92), (92, 93), (93, 94), (94, 95), (95, 96), (96, 97), (97, 98), (98, 99), (99, 100), (100, 101), (101, 102), (102, 103), (103, 104), (104, 105), (105, 106), (106, 107)]

In [ ]:
url = "https://raw.githubusercontent.com/sayashraaj/Dump/main/Days_csv.csv"
df_days = pd.read_csv(url)
df_days.head(60)

,ID,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Daily,Mon,Tue,Wed,Thu,Fri,Sat,Sun,Src Stn
0,1661,Tue,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False,False,False,HBJ
1,1662,Wed,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,False,False,False,PURI
2,1663,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,DWR
3,1664,Fri,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,True,False,False,HBJ
4,1665,Wed,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,False,False,False,HBJ
5,1666,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,AGTL
6,1705,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,BDTS
7,1706,Thu,NaN,NaN,NaN,NaN,NaN,False,False,False,False,True,False,False,False,JBP
8,1707,Tue,Sat,NaN,NaN,NaN,NaN,False,False,True,False,False,False,True,False,JBP
9,1708,Sun,Wed,NaN,NaN,NaN,NaN,False,False,False,True,False,False,False,True,ATT
10,2193,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,TEN
11,2194,Thu,NaN,NaN,NaN,NaN,NaN,False,False,False,False,True,False,False,False,JBP
12,2195,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,REWA
13,2196,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,BPL
14,2197,Mon,NaN,NaN,NaN,NaN,NaN,False,True,False,False,False,False,False,False,CBE
15,2198,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,JBP
16,2485,Thu,NaN,NaN,NaN,NaN,NaN,False,False,False,False,True,False,False,False,NED
17,2486,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,NZM
18,2731,Fri,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,True,False,False,HYB
19,2732,Sun,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,True,JP
20,2833,Mon,NaN,NaN,NaN,NaN,NaN,False,True,False,False,False,False,False,False,RJT
21,4767,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,HMH
22,4768,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SGNR
23,4769,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,HMH
24,4770,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SGNR
25,4773,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SGNR
26,4774,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SOG
27,4775,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SDLP
28,4776,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,HMH
29,4777,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SDLP
30,4778,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,HMH
31,4782,Tue,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False,False,False,BEAS
32,4801,Mon,Tue,Wed,Thu,Fri,Sat,False,True,True,True,True,True,True,False,PBC
33,4802,Sun,Mon,Tue,Wed,Thu,Fri,False,True,True,True,True,True,False,True,MKN
34,4805,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,AWR
35,4806,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,KRH
36,4851,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,MTD
37,4852,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,RTGH
38,4853,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,RTGH
39,4854,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,CUR
40,5305,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,FBD
41,5306,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,FBD
42,5309,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,BC
43,5310,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,LKU
44,5521,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,JMP
45,5522,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SHC
46,5613,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,JLWC
47,5614,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,KOTA
48,5683,Sat,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,True,False,BIR
49,5684,Mon,NaN,NaN,NaN,NaN,NaN,False,True,False,False,False,False,False,False,ET
50,6001,Fri,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,True,False,False,MS
51,6002,Sun,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,True,TEN
52,6005,Fri,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,True,False,False,MAS
53,6006,Sun,NaN,NaN,NaN,NaN,NaN,False,False,False,False,False,False,False,True,ERS
54,6007,Tue,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False,False,False,MAS
55,6008,Wed,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,False,False,False,NCJ
56,6011,Mon,NaN,NaN,NaN,NaN,NaN,False,True,False,False,False,False,False,False,SCT
57,6012,Daily,NaN,NaN,NaN,NaN,NaN,True,False,False,False,False,False,False,False,SA
58,6012,Tue,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,False,False,False,SA
59,6083,Mon,Tue,Wed,Thu,Fri,Sat,False,True,True,True,True,True,True,False,CBE

In [ ]:
# Checking for faulty links
test_idx=80
print(nodesList[test_idx].TrainId, nodesList[test_idx].TrainName, nodesList[test_idx].StationName, nodesList[test_idx].Time, nodesList[test_idx].Day)
printConnectedTo(test_idx)

22982 SRIGANGANAGAR - KOTA SF EXPRESS  MAKRANA JUNCTION 02:50 2
Node details 22982 02:50 2
Printing connectedTo for Node 80
Connection: 22982 03:22 2
----------------------